---
apiVersion: v1
kind: Namespace
metadata:
  name: acm-applications

---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: acm-policies-channel
  namespace: acm-applications
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
    apps.open-cluster-management.io/webhook-enabled: "true"
    # apps.open-cluster-management.io/webhook-secret=<the_secret_name>
spec:
    type: Git
    pathname: https://github.com/Red-Hat-Demo-Use-Cases/acm-aks-management.git
    secretRef:
      name: acm-policies-channel-git-secret
    insecureSkipVerify: true


---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: feature1
    apps.open-cluster-management.io/git-path: /manifests/acm-policies
    apps.open-cluster-management.io/reconcile-rate: high
  name: acm-policies-subscription
  namespace: acm-applications
spec:
  channel: acm-applications/acm-policies-channel
  placement:
    local: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:subscription-admin
rules:
- apiGroups:
  - app.k8s.io
  resources:
  - applications
  verbs:
  - '*'
- apiGroups:
  - apps.open-cluster-management.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - namespaces
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:subscription-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:subscription-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: redhat-acm-application-subscription-admin


